- id: nonemoji
  name: nonemoji
  entry: nonemoji hook
  language: python
  description: "Simple gitmoji cli written in python"
  require_serial: true
  minimum_pre_commit_version: "2.9.2"
  stages: [prepare-commit-msg]
